import './global.css';

export const metadata = {
  title: 'Welcome to Spawntech',
  description: 'Generated by create-nx-workspace, enhanced by @spwn/',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
