name: CI
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!preview'
      - '!main'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: volta-cli/action@v4
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm ci
