name: CI
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: volta-cli/action@v4
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx affected -t lint
      - run: npx nx affected -t test --configuration=ci
      - run: npx nx affected -t build
      - run: npx nx affected -t build-storybook
